.idea/.gitignore
.idea/compiler.xml
.idea/final_project.iml
.idea/gradle.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
DDIS_HR/.gitignore
DDIS_HR/build.gradle
DDIS_HR/src/main/java/com/ddis/ddis_hr/S3Config/config/S3Config.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/S3Config/controller/S3Controller.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/S3Config/service/S3Service.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/S3Config/service/S3ServiceImpl.java

1. S3 Config 설정
2. Postman 테스트
- close #1 

[feat] yml 파일 git upload 방지를 위한 확인

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/DepartmentDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/HeadquartersDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/JobDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/PositionDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/RankDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/dto/TeamDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dao/SalaryMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/EmployeeSearchCondition.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/EmployeeSummaryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalaryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalaryDetailDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalarySearchCondition.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/SalarySummaryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/EmployeeSearchService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/SalaryQueryService.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/SalaryMapper.xml

1. 사원필터조회
2. 사원급여요약(기간)
3. 해당사원&해당월급여상세
- #11 
> review dummy 안들어가서 주석처리하고 진행했습니다. 올리진 않았어요
> goal 관련된 entity가 전부 member 내에 있어서, 따로 생성하였습니다 (사원, 직무 및 조직)
> 제가 따로 쓴 DTO는 별칭 달아서 진행했습니다..!

[FEAT] 급여명세서 조회 (인사) API 구현

---

DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql

1. 전자결재 관련 더미 수정 및 추가  -> 테스트 완료
2. 평가 테이블 DDL 수정 (PK-> autoincrement 추가)
> 
*코드 테스트 진행을 위한 간소화된 더미 추가 (1번 양식에 대한 테스트더미)
- 전자결재양식 (1번 양식만 추가)
- 전자결재기안문서
- 문서결재함
- 결재라인
- 첨부파일

[REFACTOR] 전자결재 더미데이터 수정

---

DDIS_HR/src/main/resources/sql/ddis_fin_dummy.sql
DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql

1. 충돌 스키마, 더미 수정
> 브랜치 삭제 부탁드립니다

[CHORE] 스키마, 더미 수정

---

DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql

[REFACTOR] 테이블 생성 문자셋 utf8mb4 지정

---

DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql

1. employee_id_reviewer NOT NULL 조건 제거

[REFACTOR] DDL 수정  selfreview에서 employee_id_reviewer NOT NULL 조건 제거

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/RetirementQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dao/RetirementMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementDetailDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementSearchCondition.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/dto/RetirementSummaryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/RetirementQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/service/RetirementQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/payroll/query/mapper/RetirementMapper.xml

1. 퇴직금 지급일자 필터
2. 퇴직금 퇴직일자 필터
3. 퇴직금 상세정보 조회
4. 급여 부분 엔티티 변경
- #25 
> 급여명세서랑 더미가 안 맞는 부분이 있어서 추후 수정하겠습니다..!

[FEAT] 퇴직금 지급현황 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeHrDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeePublicDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml

1. 사원 목록 조회 API 구현
2. Postman 테스트
3. Restful API 
- close #39 
>

사원 목록 조회 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/DisciplinaryMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/MyDisciplinaryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java

1. 내 징계 조회 API 구현
2. Postman 테스트
3. Restful API 적용
- close #43 
> ![내_징계_조회](https://github.com/user-attachments/assets/55fc2bbd-52ac-4d84-96c4-85b17b79dea3)

[FEAT] 내 징계 조회 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/MyWorkStatusQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml

[FEAT] 내 근무 현황 API 구현

---

DDIS_HR/src/main/resources/com/ddis/ddis_hr/menu/query/mapper/FavoriteMenuMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/menu/query/mapper/MenuMapper.xml

[FEAT] 메뉴 mapper.xml 추가

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml

[FEAT] 오늘 개인 일정 조회 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/controller/AttendanceQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dao/AttendanceMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/dto/WeeklyOvertimeSummaryQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml

1. 주간 초과 근무 시간 조회 API 구현
- #76 
- 초과 근무 시간은 분 단위로 저장되므로 프론트에서 시간 단위로 환산하는 과정 필요함. (프론트 참고)

[FEAT] 주간 초과 근무 시간 조회 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/ApprovalLineDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/ApprovalLineRequestDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateResponseCommandDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApproverQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ContentQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocFormQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/FileQueryDTO.java

[REFACTOR] fileDTO추가

---

.idea/.gitignore
.idea/BE.iml
.idea/compiler.xml
.idea/dataSources.xml
.idea/gradle.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeEnrollDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/repository/EmployeesRepository.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/application/dto/EmployeeDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/domain/aggregate/entity/Employee.java

1. 사원 등록 API 구현
2. Postman 테스트
3. Restful API 적용
>
>

[FEAT] 사원 등록 API 구현

---

.idea/dataSources.xml
DDIS_HR/src/main/java/com/ddis/ddis_hr/common/GlobalExceptionHandler.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeHrUpdateDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeUpdateDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java

1. 사원 정보 수정 API 구현
2. Postman 테스트
3. Restful API 구현
- close #83 
> 인사팀, 사용자마다의 수정 범위를 다르게 구현 (인사팀 수정 API는 주석 처리 해놓음)

[FEAT] 사원 정보 수정 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/ApprovalLineCommandServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/domain/entity/ApprovalLine.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalDocumentQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.xml

1. 결재함 결재 조회 프론트와 연동하여 구현
2. 2
3. 3

[FEAT] 결재함 결재 조회 생성

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java

[REFACTOR] S3 로직 추가

---

.gitignore

[REFACTOR] gitignore 수정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml

1. EmployeeListDTO에 생일 추가 for 리마인더 이벤트

[FEAT] 사원 생일 추가

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/aggregate/Attendance.java

1. 근무상태별 출퇴근 등록 조건 변경
2. 근무시간 등록

[REFACTOR] 근무상태별 출퇴근 등록 조건 변경, 근무시간 등록 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/DdisHrApplication.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AbsenceScheduler.java

1. 결근 처리 스케줄러 구현
- 매일 12:00 출근 기록이 없는 사원은 결근으로 등록

[FEAT] 결근 처리 스케줄러 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalDocumentQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/ApprovalLineQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DrafterQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineResponseDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/ApprovalLineTemplateDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DraftDetailResponseQueryDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftDocumentMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/ApprovalDocumentQueryServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DrafterQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml

1. 결재함 api 구현
2. 결재함 프론트 연동
3. 결재함 테스트 진행
- #120 

[FEAT] 전자결재 결재함 구현 api

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/EmployeeMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml

1. 프론트와 연동을 위한 수정
- close #123 

[REFACTOR] 사원 정보 상세 조회

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/DisciplinaryQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dao/DisciplinaryMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/DisciplinaryQueryServiceImpl.java

[FIX] DisciplinaryListDTO 주석 처리

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/controller/AttendanceCommandController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/dto/OvertimeRequestDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/service/AttendanceCommandServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/domain/repository/AttendanceRepository.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/query/service/AttendanceQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/attendance/query/mapper/AttendanceMapper.xml

[FEAT] 초과 근무 신청 API 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/controller/DraftQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftQueryServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml

[FEAT] 전자결재 회수 api 구현

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/controller/PayrollMailController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/command/application/controller/RetirementMailController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/PayrollQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/payroll/query/controller/RetirementQueryController.java

1. 토큰 반영해서 본인 정보 가져오는 api 추가
2. 권한 설정
- #138 

[REFACTOR] 급여 권한 설정 및 api 수정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/controller/DraftCommandController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/organization/query/mapper/appointmentHistoryMapper.xml

1. 백엔드 연동을 위한 매퍼 수정
2. 오류 코드 주석 처리
- close #160 

[REFACTOR] 백엔드 연동을 위한 매퍼 수정, 오류 코드 주석 처리

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/controller/EmployeeController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/dto/EmployeeHrUpdateDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/controller/EmployeeQueryController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/service/EmployeeQueryServiceImpl.java

[REFACTOR] 사원 조회 권한 설정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/AppointmentController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/IntroductionController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/JobController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/controller/StructureController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/query/controller/AppointmentQueryController.java
DDIS_HR/src/test/java/com/ddis/ddis_hr/organization/TeamRegisterTests.java

[FEAT] 인사팀 권한 설정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/controller/FavoriteMenuCommandController.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/dto/FavoriteMenuOrderChangeDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/application/service/FavoriteMenuCommandServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/aggregate/FavoriteMenu.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/command/domain/repository/FavoriteMenuRepository.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/menu/query/controller/FavoriteMenuQueryController.java

1. 기본 프론트에서 id값 넘김 -> 프론트에서 token 넘김 방식 수정에 따라 전반적인 수정
- #166 

[REFACTOR] 자주 쓰는 메뉴 api 방식 변경

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/dto/DraftCreateCommandDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/dto/DocumentDTO.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftDetailService.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/query/service/DraftDetailServiceImpl.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/ApprovalDocumentMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DocumentBoxMapper.xml
DDIS_HR/src/main/resources/com/ddis/ddis_hr/eapproval/query/mapper/DraftMapper.xml

1. 기안문 상세조회 내 수신자, 참조자 렌더링 구현
2. 기안문 상세조회 내 젠체 데이터 프론트 연동 확인
- #170 

[FEAT] 기안문 상세조회 내 수신자, 참조자 렌더링 구현

---

.github/workflows/cr.yml
.gitignore
DDIS_HR/.ebextensions/app.config
DDIS_HR/.platform/nginx.conf
DDIS_HR/Procfile
DDIS_HR/build.gradle

[FEAT] github action을 위한 yml 추가

---

.github/workflows/cr.yml

[FEAT] 배포 버전 중복 방지

---

.github/workflows/cr.yml

[REFACTOR] EOL -> EOF

---

.github/workflows/cr.yml

[FEAT] 배포 테스트

---

.github/workflows/cr.yml

[TEST] 배포 테스트

---

.github/workflows/cr.yml

[REFACTOR] yml 수정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/member/security/WebSecurity.java

[FIX] 배포 cors 설정

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/application/service/EmployeeServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/command/domain/repository/EmployeesRepository.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/member/command/domain/aggregate/entity/Employee.java
DDIS_HR/src/main/resources/sql/ddis_fin_schema.sql

1. 사원 등록, 수정 시 낙관적 lock 적용
2. Entity 수정
3. 컬럼 추가
4. ServiceImpl 리팩토링
- close #192 
> 테스트 성공 시 추가 설명 기재하도록 하겠습니다.

[FEAT] 사원 등록,수정 낙관적 lock 적용

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/healthcheck/controller/HealthCheckController.java

[RELEASE] 환경 용량 변경

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/attendance/command/application/scheduler/AttendanceScheduler.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/eapproval/command/application/service/DraftCommandServiceImpl.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/event/NoticeEvent.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/application/listener/NoticeEventListener.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/notice/command/domain/aggregate/NoticeEntity.java
DDIS_HR/src/main/java/com/ddis/ddis_hr/organization/command/application/batch/listener/AppointmentHistoryNoticeListener.java

[FEAT] 기안 등록 시 결재 요청 알림

---

DDIS_HR/src/main/java/com/ddis/ddis_hr/employee/query/dto/EmployeeListDTO.java
DDIS_HR/src/main/resources/com/ddis/ddis_hr/employee/query/mapper/EmployeeMapper.xml

[FEAT] 헤더 프로필 url 추가
